### ISSUE TITLE
dB ranges for your VAD?

### ISSUE THREAD

**Issue by yosun** [mapluisch/OpenAI-Realtime-API-for-Unity#1]
Can't seem to get your VAD to work - have you looked into Whisper VAD? 

https://github.com/Macoron/whisper.unity

**Comment by yosun** [comment]
https://github.com/Macoron/whisper.unity/blob/275406258aca21fe7753cf0724a65f06fd464eea/Packages/com.whisper.unity/Runtime/Utils/AudioUtils.cs#L69

**Comment by mapluisch** [comment]
Hey yosun, 
thanks for sharing! That looks great - will use it to replace my basic VAD approach.

**Comment by mapluisch** [comment]
Hey yosun,
just wanted to let you know that I've integrated Whisper VAD (to the best of my knowledge 😅) - hope it works on your end. You might have to tinker around with the threshs in the Audio-Prefab.

**Comment by yosun** [comment]
VAD seems to cut off the response voice before it starts?

Also it seems that longer than 30s or 1 minute voice files do not get sent? (hangs in "recording stopped sending audio")
