### ISSUE TITLE
Audio loopback issue

### ISSUE THREAD

**Issue by from2001** [mapluisch/OpenAI-Realtime-API-for-Unity#2]
Hi @mapluisch 
Thank you for the great library.

I tried the demo on my Mac, and the program worked great with manual mode.
However, with the vad mode, the audio response of the realtime API loops back to the microphone input. Doesn't this happen on your environment? 

I made sure that the script use `MacBook Pro Microphone` as the microphone device, which should work fine.

https://github.com/user-attachments/assets/ed2494b4-31c2-421f-8263-db4b19358f16

**Comment by from2001** [comment]
I tried with my Windows environment now, and it works fine. I'll take a look at my Mac settings.

**Comment by from2001** [comment]
It was solved with an external headset. I'll close this issue.

**Comment by from2001** [comment]
It's just a note.
I deleted audio deriver for Zoom and Teams, which are located at `/Library/Audio/Plug-Ins/HAL` on Mac, and the problem was solved even without an external headset.

**Comment by mapluisch** [comment]
Thanks for the update - perhaps I could add acoustic echo cancellation in a future update, will add it to the backlog.
